/**
 * LLM 集成接口层
 * 为接入 Claude/GPT 等真实 LLM 做准备
 * 当前为模拟实现，可替换为真实 API 调用
 */

import { EventEmitter } from 'events';

export interface LLMConfig {
  provider: 'anthropic' | 'openai' | 'local' | 'mock';
  apiKey?: string;
  baseUrl?: string;
  model: string;
  maxTokens: number;
  temperature: number;
}

export interface LLMMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface LLMResponse {
  content: string;
  usage: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
  model: string;
  finishReason: string;
}

export interface LLMStreamChunk {
  content: string;
  done: boolean;
}

// ==================== LLM Provider 抽象基类 ====================

export abstract class LLMProvider extends EventEmitter {
  protected config: LLMConfig;

  constructor(config: LLMConfig) {
    super();
    this.config = config;
  }

  abstract chat(messages: LLMMessage[]): Promise<LLMResponse>;
  abstract chatStream(messages: LLMMessage[]): AsyncGenerator<LLMStreamChunk>;
  abstract validate(): Promise<boolean>;
}

// ==================== Mock Provider（模拟实现） ====================

export class MockLLMProvider extends LLMProvider {
  async chat(messages: LLMMessage[]): Promise<LLMResponse> {
    const lastMessage = messages[messages.length - 1];
    const content = this.generateMockResponse(lastMessage.content);

    this.emit('response', { content, model: this.config.model });

    return {
      content,
      usage: {
        promptTokens: this.estimateTokens(messages),
        completionTokens: this.estimateTokens([{ role: 'assistant', content }]),
        totalTokens: this.estimateTokens(messages) + this.estimateTokens([{ role: 'assistant', content }]),
      },
      model: this.config.model,
      finishReason: 'stop',
    };
  }

  async *chatStream(messages: LLMMessage[]): AsyncGenerator<LLMStreamChunk> {
    const response = await this.chat(messages);
    const words = response.content.split(' ');

    for (let i = 0; i < words.length; i++) {
      yield {
        content: words[i] + ' ',
        done: i === words.length - 1,
      };
    }
  }

  async validate(): Promise<boolean> {
    return true;
  }

  private generateMockResponse(input: string): string {
    const responses: Record<string, string> = {
      'code': `// 模拟生成的代码
function generateCode() {
  console.log('Generated by AI');
  return true;
}`,
      'test': `describe('Generated Test', () => {
  it('should pass', () => {
    expect(true).toBe(true);
  });
});`,
      'architecture': `## 架构建议

基于当前需求，推荐采用分层架构：
1. 表现层：处理用户交互
2. 业务层：核心业务逻辑
3. 数据层：持久化存储

理由：关注点分离，便于测试和维护。`,
      'default': `基于您的输入，我提供以下建议：

1. 分析需求并明确目标
2. 设计合适的架构方案
3. 逐步实现并持续测试
4. 审查代码质量

请提供更多上下文以获得更精确的建议。`,
    };

    for (const [key, value] of Object.entries(responses)) {
      if (input.toLowerCase().includes(key)) {
        return value;
      }
    }

    return responses['default'];
  }

  private estimateTokens(messages: LLMMessage[]): number {
    return messages.reduce((sum, msg) => sum + Math.ceil(msg.content.length / 4), 0);
  }
}

// ==================== Anthropic Provider（Claude） ====================

export class AnthropicProvider extends LLMProvider {
  async chat(messages: LLMMessage[]): Promise<LLMResponse> {
    // TODO: 实现真实的 Anthropic API 调用
    // const response = await fetch('https://api.anthropic.com/v1/messages', {
    //   method: 'POST',
    //   headers: {
    //     'Content-Type': 'application/json',
    //     'x-api-key': this.config.apiKey!,
    //   },
    //   body: JSON.stringify({
    //     model: this.config.model,
    //     max_tokens: this.config.maxTokens,
    //     messages: messages.map(m => ({ role: m.role, content: m.content })),
    //   }),
    // });

    // 当前使用模拟实现
    const mock = new MockLLMProvider(this.config);
    return mock.chat(messages);
  }

  async *chatStream(messages: LLMMessage[]): AsyncGenerator<LLMStreamChunk> {
    const mock = new MockLLMProvider(this.config);
    yield* mock.chatStream(messages);
  }

  async validate(): Promise<boolean> {
    if (!this.config.apiKey) {
      return false;
    }
    // TODO: 验证 API key 有效性
    return true;
  }
}

// ==================== OpenAI Provider（GPT） ====================

export class OpenAIProvider extends LLMProvider {
  async chat(messages: LLMMessage[]): Promise<LLMResponse> {
    // TODO: 实现真实的 OpenAI API 调用
    const mock = new MockLLMProvider(this.config);
    return mock.chat(messages);
  }

  async *chatStream(messages: LLMMessage[]): AsyncGenerator<LLMStreamChunk> {
    const mock = new MockLLMProvider(this.config);
    yield* mock.chatStream(messages);
  }

  async validate(): Promise<boolean> {
    if (!this.config.apiKey) {
      return false;
    }
    return true;
  }
}

// ==================== LLM 工厂 ====================

export class LLMFactory {
  static createProvider(config: LLMConfig): LLMProvider {
    switch (config.provider) {
      case 'anthropic':
        return new AnthropicProvider(config);
      case 'openai':
        return new OpenAIProvider(config);
      case 'mock':
      case 'local':
      default:
        return new MockLLMProvider(config);
    }
  }
}

// ==================== Agent LLM 集成 ====================

export class AgentLLMIntegration {
  private provider: LLMProvider;

  constructor(provider: LLMProvider) {
    this.provider = provider;
  }

  /**
   * 生成代码
   */
  async generateCode(task: any, context: string): Promise<string> {
    const messages: LLMMessage[] = [
      {
        role: 'system',
        content: `你是一个专业的软件工程师。请根据任务描述生成高质量的代码。

要求：
- 遵循编码规范
- 包含适当的错误处理
- 添加必要的注释
- 生成对应的单元测试

任务信息：
${JSON.stringify(task, null, 2)}

环境上下文：
${context}`,
      },
      {
        role: 'user',
        content: `请生成任务 "${task.title}" 的代码实现。`,
      },
    ];

    const response = await this.provider.chat(messages);
    return response.content;
  }

  /**
   * 生成架构建议
   */
  async generateArchitectureSuggestion(task: any, context: string): Promise<string> {
    const messages: LLMMessage[] = [
      {
        role: 'system',
        content: `你是一个资深软件架构师。请分析需求并提供架构建议。

任务信息：
${JSON.stringify(task, null, 2)}

环境上下文：
${context}`,
      },
      {
        role: 'user',
        content: `请为 "${task.title}" 提供架构设计方案，包括技术选型、模块划分和接口设计。`,
      },
    ];

    const response = await this.provider.chat(messages);
    return response.content;
  }

  /**
   * 代码审查
   */
  async reviewCode(code: string, context: string): Promise<string> {
    const messages: LLMMessage[] = [
      {
        role: 'system',
        content: `你是一个代码审查专家。请审查以下代码并提供改进建议。

环境上下文：
${context}`,
      },
      {
        role: 'user',
        content: `请审查以下代码：\n\n\`\`\`\n${code}\n\`\`\`

关注：安全性、性能、可读性、可维护性。`,
      },
    ];

    const response = await this.provider.chat(messages);
    return response.content;
  }

  /**
   * 解释决策（可解释性）
   */
  async explainDecision(decision: any, context: string): Promise<string> {
    const messages: LLMMessage[] = [
      {
        role: 'system',
        content: `请解释以下决策的理由和依据。`,
      },
      {
        role: 'user',
        content: `决策信息：\n${JSON.stringify(decision, null, 2)}\n\n上下文：\n${context}\n\n请解释为什么做出这个决策。`,
      },
    ];

    const response = await this.provider.chat(messages);
    return response.content;
  }
}

export { LLMProvider, MockLLMProvider, AnthropicProvider, OpenAIProvider, LLMFactory, AgentLLMIntegration };
